services:
  # Web Service for our Express backend app
  - type: web
    name: url-shortener-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx prisma db push && npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: shortener-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: shortener-cache
          property: connectionString

databases:
  # Managed PostgreSQL database (Free Tier)
  - name: shortener-db
    plan: free

interfaces:
  # Managed Redis Cache (Free Tier)
  - type: redis
    name: shortener-cache
    plan: free
